### ISSUE TITLE
Question: project name is megalist or megalista?

### ISSUE THREAD

**Issue by joaquimsn** [google/megalista#15]
I have a doubt, @astivi and @caiotomazelli 

The name of the repository and documentation is Megalista
But the folder structure uses the name megalist and some parameters as well.

We understand that the name of the solution is Megalista, and all coding must use the megalist nomenclature. Is correct?

**Comment by astivi** [comment]
Hey there!

Actually we wanted to rename everything to Megalista, we just didn't do that yet =(

Cheers,
Álvaro.

**Comment by joaquimsn** [comment]
Hi,

Thanks for your response.

I will open a PR for this refactoring. ;)
