### ISSUE TITLE
Documentation mismatch in Google Ads Customer Match Device ID schema

### ISSUE THREAD

**Issue by xfer** [google/megalista#17]
According to the [documentation,](https://github.com/google/megalista/wiki/Google-Ads-Customer-Match---Device-Id#expected-schema) the expected schema for Google Ads Customer Match Device ID table is 
| Column name | Type | Description | Requirement |
| :---: | :---: | :---: | :---: |
|  mobile_device_id | STRING | Mobile device Id identifier (android AdId or IOS IDFA) | **required** |

But in the [source code](https://github.com/google/megalista/blob/main/megalist_dataflow/uploaders/google_ads/customer_match/mobile_uploader.py#L49), the field is `mobileId`.

```python
def get_row_keys(self) -> List[str]:
    return ['mobileId']
```

**Comment by astivi** [comment]
Hey there xfer, thanks for raising this up!

I believe that the documentation is correct.

In the [mapper code](https://github.com/google/megalista/blob/main/megalist_dataflow/mappers/ads_user_list_pii_hashing_mapper.py#L73) you can see that is renames que BigQuery column from mobile_device_id to the mobileId key.

**Comment by astivi** [comment]
Closing this up. Feel free to reopen if any questions should arise.
