### ISSUE TITLE
[Docs] Possible outdated documentation

### ISSUE THREAD

**Issue by wesleytanws** [google/megalista#51]
We have identified **`1`** possible instance of outdated documentation:

- [x] [`megalist_dataflow`](https://github.com/google/megalista/blob/1f8cde4c15febb510a516318f92b5e96b308aaae/terraform/scripts/deploy_cloud.sh#L22) was renamed to [`megalista_dataflow`](https://github.com/google/megalista/blob/86dc92c8a211b0c9af524581385bb8a3d89cac63/terraform/scripts/deploy_cloud.sh#L22) but the change has not been reflected in the current version of the [Update instructions](https://github.com/google/megalista/wiki/Update-instructions/b72b13d90333d40384194f97a333d4732d80033b) wiki page

#### About
This is part of a research project that aims to automatically detect outdated documentation in GitHub repositories. We are evaluating the validity of our approach by identifying instances of outdated documentation in real-world projects.

We hope that this research will be a step towards keeping documentation up-to-date. If this has been helpful, consider updating the documentation to keep it in sync with the source code. If this has not been helpful, consider updating this issue with an explanation, so that we can improve our approach. Thanks!

**Comment by wesleytanws** [comment]
Friendly ping :)

**Comment by antoniolmm** [comment]
Thanks, there really was an error.
